#!/bin/bash
# smart-review.sh - Интеллектуальный code review с контекстом стека

set -e

PR_NUMBER="${1:-}"
STACK_CONFIG="${2:-react-node}"
REVIEW_DEPTH="${3:-standard}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

if [ -z "$PR_NUMBER" ]; then
    echo -e "${RED}Error: PR number is required${NC}"
    echo "Usage: $0 <pr-number> [stack-config] [review-depth]"
    echo "Review depth: quick, standard, thorough, security"
    exit 1
fi

echo -e "${BLUE}🔍 Smart Code Review Agent${NC}"
echo -e "PR: #$PR_NUMBER"
echo -e "Stack: $STACK_CONFIG"
echo -e "Depth: $REVIEW_DEPTH"
echo ""

# Загружаем конфигурацию стека
STACK_FILE="configs/stacks/${STACK_CONFIG}.json"
if [ ! -f "$STACK_FILE" ]; then
    echo -e "${RED}Error: Stack configuration not found: $STACK_FILE${NC}"
    exit 1
fi

# Получаем информацию о PR
echo -e "${YELLOW}📥 Fetching PR information...${NC}"
gh pr view "$PR_NUMBER" --json title,body,author,files > "pr-${PR_NUMBER}-info.json"
gh pr diff "$PR_NUMBER" > "pr-${PR_NUMBER}-diff.patch"

# Определяем уровень review
case "$REVIEW_DEPTH" in
    "quick")
        REVIEW_FOCUS="syntax, basic logic, obvious bugs"
        MAX_TURNS=3
        ;;
    "standard")
        REVIEW_FOCUS="code quality, best practices, performance, maintainability"
        MAX_TURNS=5
        ;;
    "thorough")
        REVIEW_FOCUS="architecture, design patterns, scalability, comprehensive testing"
        MAX_TURNS=8
        ;;
    "security")
        REVIEW_FOCUS="security vulnerabilities, data validation, authentication, authorization"
        MAX_TURNS=6
        ;;
    *)
        REVIEW_FOCUS="code quality, best practices, performance, maintainability"
        MAX_TURNS=5
        ;;
esac

echo -e "${YELLOW}🧠 Analyzing changes with Claude...${NC}"

# Создаем детальный промпт для review
REVIEW_PROMPT="
You are an expert code reviewer specializing in $(jq -r '.name' "$STACK_FILE").

**Stack Configuration:**
$(cat "$STACK_FILE")

**PR Information:**
$(cat "pr-${PR_NUMBER}-info.json")

**Code Changes:**
\`\`\`diff
$(cat "pr-${PR_NUMBER}-diff.patch")
\`\`\`

**Review Focus:** $REVIEW_FOCUS

Please provide a comprehensive code review including:

1. **Overview** - Summary of changes and their purpose
2. **Code Quality** - Adherence to best practices for this stack
3. **Architecture** - Design decisions and patterns used
4. **Performance** - Potential performance implications
5. **Security** - Security considerations and vulnerabilities
6. **Testing** - Test coverage and quality
7. **Specific Issues** - Line-by-line feedback with file:line references
8. **Recommendations** - Concrete suggestions for improvement
9. **Approval Status** - Approve, Request Changes, or Comment

For each issue found, provide:
- File and line number
- Severity (critical, major, minor, suggestion)
- Detailed explanation
- Suggested fix

Format the output as structured markdown for easy GitHub integration.
"

# Запускаем Claude review
claude -p "$REVIEW_PROMPT" \
    --output-format json \
    --max-turns "$MAX_TURNS" \
    > "review-${PR_NUMBER}-${REVIEW_DEPTH}.json"

# Извлекаем review
jq -r '.result' "review-${PR_NUMBER}-${REVIEW_DEPTH}.json" > "review-${PR_NUMBER}-${REVIEW_DEPTH}.md"

echo -e "${GREEN}✅ Review completed: review-${PR_NUMBER}-${REVIEW_DEPTH}.md${NC}"

# Проверяем если нужно автоматически постить комментарий
if command -v gh >/dev/null 2>&1; then
    echo -e "${YELLOW}💬 Posting review comment...${NC}"
    
    # Создаем комментарий с review
    COMMENT_BODY="## 🤖 Automated Code Review

**Stack:** $(jq -r '.name' "$STACK_FILE")  
**Review Depth:** $REVIEW_DEPTH  
**Generated:** $(date)

$(cat "review-${PR_NUMBER}-${REVIEW_DEPTH}.md")

---
*Generated by Claude Squad Smart Review Agent*"

    # Постим комментарий
    gh pr comment "$PR_NUMBER" --body "$COMMENT_BODY"
    
    echo -e "${GREEN}✅ Review comment posted to PR #${PR_NUMBER}${NC}"
fi

# Создаем метрики review
echo -e "${YELLOW}📊 Generating review metrics...${NC}"

METRICS_PROMPT="
Based on the code review analysis, generate metrics and insights:

**Review Data:**
$(cat "review-${PR_NUMBER}-${REVIEW_DEPTH}.md")

Generate:
1. Code quality score (1-10)
2. Security risk level (low, medium, high)
3. Performance impact assessment
4. Maintainability score
5. Test coverage assessment
6. Recommended actions summary

Output as JSON format for tracking and analytics.
"

claude -p "$METRICS_PROMPT" \
    --output-format json \
    --max-turns 3 \
    > "metrics-${PR_NUMBER}-${REVIEW_DEPTH}.json"

# Извлекаем метрики
jq -r '.result' "metrics-${PR_NUMBER}-${REVIEW_DEPTH}.json" > "metrics-${PR_NUMBER}-${REVIEW_DEPTH}-data.json"

echo -e "${BLUE}📋 Review Summary:${NC}"
echo -e "- Detailed review: review-${PR_NUMBER}-${REVIEW_DEPTH}.md"
echo -e "- Review data: review-${PR_NUMBER}-${REVIEW_DEPTH}.json"
echo -e "- PR information: pr-${PR_NUMBER}-info.json"
echo -e "- Code changes: pr-${PR_NUMBER}-diff.patch"
echo -e "- Metrics: metrics-${PR_NUMBER}-${REVIEW_DEPTH}-data.json"

# Показываем краткие метрики если получились
if [ -f "metrics-${PR_NUMBER}-${REVIEW_DEPTH}-data.json" ]; then
    echo -e "\n${BLUE}📊 Quick Metrics:${NC}"
    echo -e "$(cat "metrics-${PR_NUMBER}-${REVIEW_DEPTH}-data.json" | head -10)"
fi

echo -e "\n${GREEN}🎉 Smart review completed!${NC}"